default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  password:
  username: